language: node_js
node_js: lts/*
os: osx
osx_image: xcode10.2
env:
  global:
    - CSC_IDENTITY_AUTO_DISCOVERY=false
before_install:
  - brew update
install:
  - yarn install
script:
  - yarn test --coverage
before_deploy:
  - yarn release -mwl
deploy:
  provider: releases
  api_key:
    secure: qLlU0etZodfMmpjKVgIzjCHKDjz2f0FIolKd+RKlI3X3xvmX7/cesI+8OKS7trEMsWRNdoAfKUvn0JzuJvf6DiFcdBvnVcDzFKBYtd2mY4eKTq6UotPqlnb2RC/7kRsspNjWb3cEN1v9IQAWnMPz3y72kOl185taiFA8WY29TKIdPN/QgvDqwP8fI7RLVvnqDt1xchmccSiTLzyPiZR+JH4cw1YRJyenCvW3dWz3SX2Y8nq0JwdmvgTIVW7RVIA+RD13b7isdoc2EnaF6TNbTYSZKhY++kQJy7/RlZguBANrkFhyxy/VOgqpG6T1ON1PLX3nWw2BdPMRkFB727dm/yhgnRc2+RZulLfWWyGSVAJ26zTApopLJwH3V5KbEji6cv5SSBw6urWipdtL5h7r18hm38Ct1PHVbof2H/Nwncsn/EUxyKUOL7jRl19gMpAkNX3fFY8/gspTsmK7HBIaUeOgyc6x2ulr0rBobsr8+0cKCHR5VrQjv3YSF5yeD7KXSgAZhLQUkGi7PifGKpcJrjdj1cri8bjsmNMlpmGWBPgy+Od2zFQqqrA0XhJuFF1MZ+KSUm1vkfcE3E7MOwYodHu+UDMvQpdIP9E+14VwfQEBhlnDyydnzhASj60SR2KvEANtNXLYdThUFovQhIQdgehQ95JipxIIbG8d9p4gySk=
  file:
    - release/ElectronReactParcel-linux.zip
    - release/ElectronReactParcel-mac.zip
    - release/ElectronReactParcel-win.zip
  skip_cleanup: true
  on:
    tags: true
    branch: master
